apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/T1kcan/kustomize-hands-on.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

